# Generated by Django 4.2.1 on 2023-05-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('codpagamento', models.IntegerField(blank=True, db_column='codpagamento', primary_key=True, serialize=False)),
                ('tipopagamento', models.CharField(choices=[('C', 'Confirmado'), ('P', 'Previsto')], db_column='tipopagamento', max_length=1)),
                ('datapagamento', models.DateField(db_column='datapagamento')),
                ('valorpagamento', models.DecimalField(db_column='valorpagamento', decimal_places=2, max_digits=10)),
                ('formapagamento', models.CharField(blank=True, db_column='formapagamento', max_length=255, null=True)),
                ('observacao', models.CharField(blank=True, db_column='observacao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'pagamentos',
                'managed': False,
            },
        ),
    ]
