# Generated by Django 4.2.1 on 2023-05-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContasPagar',
            fields=[
                ('codcontapagar', models.IntegerField(blank=True, db_column='codcontapagar', primary_key=True, serialize=False)),
                ('parcela', models.CharField(blank=True, db_column='parcela', max_length=255, null=True)),
                ('datavencimento', models.DateField(blank=True, db_column='datavencimento', null=True)),
                ('valorparcela', models.DecimalField(blank=True, db_column='valorparcela', decimal_places=2, max_digits=10, null=True)),
                ('datapagamento', models.DateField(blank=True, db_column='datapagamento', null=True)),
                ('formapagamento', models.CharField(blank=True, db_column='formapagamento', max_length=255, null=True)),
                ('observacao', models.CharField(blank=True, db_column='observacao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'contaspagar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotasFiscais',
            fields=[
                ('codnotafiscal', models.IntegerField(blank=True, db_column='codnotafiscal', primary_key=True, serialize=False)),
                ('numeronotafiscal', models.CharField(blank=True, db_column='numeronotafiscal', max_length=255, null=True)),
                ('datanotafiscal', models.DateField(blank=True, db_column='datanotafiscal', null=True)),
                ('valornotafiscal', models.DecimalField(blank=True, db_column='valornotafiscal', decimal_places=2, max_digits=10, null=True)),
                ('observacao', models.CharField(blank=True, db_column='observacao', max_length=255, null=True)),
                ('formapagamento', models.CharField(blank=True, db_column='formapagamento', max_length=255, null=True)),
            ],
            options={
                'db_table': 'notasfiscais',
                'managed': False,
            },
        ),
    ]
