# Generated by Django 4.1.7 on 2023-03-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotasFiscais",
            fields=[
                (
                    "codnotafiscal",
                    models.IntegerField(
                        blank=True,
                        db_column="codnotafiscal",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numeronotafiscal",
                    models.CharField(
                        blank=True,
                        db_column="numeronotafiscal",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "datanotafiscal",
                    models.DateTimeField(
                        blank=True, db_column="datanotafiscal", null=True
                    ),
                ),
                (
                    "valornotafiscal",
                    models.FloatField(
                        blank=True, db_column="valornotafiscal", null=True
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, db_column="observacao", max_length=255, null=True
                    ),
                ),
                (
                    "formapagamento",
                    models.CharField(
                        blank=True,
                        db_column="formapagamento",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "notasfiscais",
                "managed": False,
            },
        ),
    ]
