# Generated by Django 3.2.18 on 2023-04-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasPagar',
            fields=[
                ('codcontapagar', models.IntegerField(blank=True, db_column='codcontapagar', primary_key=True, serialize=False)),
                ('parcela', models.CharField(blank=True, db_column='parcela', max_length=255, null=True)),
                ('datavencimento', models.DateField(blank=True, db_column='datavencimento', null=True)),
                ('valorparcela', models.DecimalField(blank=True, db_column='valorparcela', decimal_places=2, max_digits=10, null=True)),
                ('datapagamento', models.DateField(blank=True, db_column='datapagamento', null=True)),
                ('formapagamento', models.CharField(blank=True, db_column='formapagamento', max_length=255, null=True)),
                ('observacao', models.CharField(blank=True, db_column='observacao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'contaspagar',
                'managed': False,
            },
        ),
    ]
