# Generated by Django 4.2.1 on 2023-05-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucoes',
            fields=[
                ('coddevolucao', models.IntegerField(blank=True, db_column='coddevolucao', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'devolucoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('codpedido', models.IntegerField(blank=True, db_column='codpedido', primary_key=True, serialize=False)),
                ('numeropedido', models.CharField(blank=True, db_column='numeropedido', max_length=255, null=True)),
                ('tipopedido', models.CharField(choices=[('C', 'Compra'), ('D', 'Devolução')], db_column='tipo_pedido', max_length=1)),
                ('datapedido', models.DateField(blank=True, db_column='datapedido', null=True)),
                ('valorpedido', models.DecimalField(db_column='valorpedido', decimal_places=2, max_digits=10)),
                ('observacao', models.CharField(blank=True, db_column='observacao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('codproduto', models.IntegerField(blank=True, db_column='codproduto', primary_key=True, serialize=False)),
                ('codprodutofornecedor', models.CharField(blank=True, db_column='codprodutofornecedor', max_length=255, null=True)),
                ('referencia', models.CharField(blank=True, db_column='referencia', max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, db_column='descricao', max_length=255, null=True)),
                ('valorcusto', models.DecimalField(blank=True, db_column='valorcusto', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'produtos',
                'managed': False,
            },
        ),
    ]
