# Generated by Django 4.1.7 on 2023-03-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "codpedido",
                    models.IntegerField(
                        blank=True,
                        db_column="codpedido",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numeropedido",
                    models.CharField(
                        blank=True, db_column="numeropedido", max_length=255, null=True
                    ),
                ),
                (
                    "codfornecedor",
                    models.IntegerField(
                        blank=True, db_column="codfornecedor", null=True
                    ),
                ),
                (
                    "codnotafiscal",
                    models.IntegerField(
                        blank=True, db_column="codnotafiscal", null=True
                    ),
                ),
                (
                    "datapedido",
                    models.DateTimeField(blank=True, db_column="datapedido", null=True),
                ),
                (
                    "valorpedido",
                    models.FloatField(blank=True, db_column="valorpedido", null=True),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, db_column="observacao", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "pedidos",
                "managed": False,
            },
        ),
    ]
