# Generated by Django 4.1.7 on 2023-03-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedidos",
            fields=[
                (
                    "codpedido",
                    models.AutoField(
                        db_column="codpedido", primary_key=True, serialize=False
                    ),
                ),
                (
                    "numeropedido",
                    models.CharField(
                        blank=True, db_column="numeropedido", max_length=255, null=True
                    ),
                ),
                (
                    "datapedido",
                    models.DateField(blank=True, db_column="datapedido", null=True),
                ),
                (
                    "valorpedido",
                    models.DecimalField(
                        blank=True,
                        db_column="valorpedido",
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, db_column="observacao", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "pedidos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "codproduto",
                    models.IntegerField(
                        blank=True,
                        db_column="codproduto",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codprodutofornecedor",
                    models.CharField(
                        blank=True,
                        db_column="codprodutofornecedor",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True, db_column="referencia", max_length=255, null=True
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, db_column="descricao", max_length=255, null=True
                    ),
                ),
                (
                    "valorcusto",
                    models.FloatField(blank=True, db_column="valorcusto", null=True),
                ),
            ],
            options={
                "db_table": "produtos",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Pedido",
        ),
    ]
