# Generated by Django 4.2.1 on 2023-05-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('codfornecedor', models.IntegerField(blank=True, db_column='codfornecedor', primary_key=True, serialize=False)),
                ('fornecedor', models.CharField(blank=True, db_column='nomefornecedor', max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, db_column='telefone', max_length=255, null=True)),
            ],
            options={
                'db_table': 'fornecedores',
                'managed': False,
            },
        ),
    ]
