# Generated by Django 4.2.1 on 2023-05-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('codvenda', models.IntegerField(blank=True, db_column='codvenda', primary_key=True, serialize=False)),
                ('datavenda', models.DateField(blank=True, db_column='datavenda', null=True)),
                ('valorvenda', models.DecimalField(blank=True, db_column='valorvenda', decimal_places=2, max_digits=10, null=True)),
                ('observacao', models.CharField(blank=True, db_column='observacao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'vendas',
                'managed': False,
            },
        ),
    ]
