# Generated by Django 3.2.18 on 2023-04-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipooperacao', models.CharField(blank=True, db_column='tipooperacao', max_length=1, null=True)),
                ('codoperacao', models.IntegerField(blank=True, db_column='codoperacao', null=True)),
                ('data', models.DateField(blank=True, db_column='data', null=True)),
                ('descricao', models.CharField(blank=True, db_column='descricao', max_length=255, null=True)),
                ('valor', models.DecimalField(blank=True, db_column='valorvenda', decimal_places=2, max_digits=10, null=True)),
                ('observacao', models.CharField(blank=True, db_column='observacao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'vw_historicocliente',
                'ordering': ['data', '-tipooperacao'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('codcliente', models.IntegerField(blank=True, db_column='codcliente', primary_key=True, serialize=False)),
                ('nomecliente', models.CharField(db_column='nomecliente', max_length=100)),
                ('telefone', models.CharField(blank=True, db_column='telefone', max_length=50, null=True)),
                ('observacao', models.CharField(blank=True, db_column='observacao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
