# Generated by Django 4.1.7 on 2023-03-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="codigo",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="id",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="nome",
        ),
        migrations.AddField(
            model_name="cliente",
            name="cliente",
            field=models.CharField(
                blank=True, db_column="nomecliente", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="codcliente",
            field=models.IntegerField(
                blank=True,
                db_column="codcliente",
                default=0,
                primary_key=True,
                serialize=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(
                blank=True, db_column="telefone", max_length=255, null=True
            ),
        ),
        migrations.AlterModelTable(
            name="cliente",
            table="clientes",
        ),
    ]
